### ISSUE TITLE
我这边加了之后造成了别的崩溃，麻烦大佬看下

### ISSUE THREAD

**Issue by chenyuEthan111** [llew2011/HuaWeiVerifier#10]
java.lang.reflect.UndeclaredThrowableException
    at $Proxy5.reportSizeConfigurations(Unknown Source)
    at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:3692)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3652)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:117)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:74)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2209)
    at com.didiglobal.booster.instrument.ActivityThreadCallback.handleMessage(ActivityThreadCallback.java:74)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7586)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    at com.xiaoniu.cleanking.room.LoadedApkHuaWei$V28VerifierImpl$AmsInvocationHandler.invoke(LoadedApkHuaWei.java:138)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    ... 14 more
Caused by: java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{f029dc8 ActivityRecord{4de7e6b u0 com.hellogeek.fycleanking/cn.jpush.android.service.DActivity t-1 f}}
    at android.os.Parcel.createException(Parcel.java:1957)
    at android.os.Parcel.readException(Parcel.java:1921)
    at android.os.Parcel.readException(Parcel.java:1871)
    at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:8738)
    ... 17 more
Caused by: android.os.RemoteException: Remote stack trace:
    at com.android.server.am.ActivityManagerService.reportSizeConfigurations(Landroid/os/IBinder;[I[I[I)V(libmapleservices.so:5928305)
    at android.app.IActivityManager$Stub.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleframework.so:4772417)
    at com.android.server.am.ActivityManagerService.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleservices.so:5940665)
    at com.android.server.am.HwActivityManagerService.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmaplehwServices.so:3389409)
    at android.os.Binder.execTransact(IJJI)Z(libmapleframework.so:6099637)
java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    at com.xiaoniu.cleanking.room.LoadedApkHuaWei$V28VerifierImpl$AmsInvocationHandler.invoke(LoadedApkHuaWei.java:138)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy5.reportSizeConfigurations(Unknown Source)
    at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:3692)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3652)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:117)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:74)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2209)
    at com.didiglobal.booster.instrument.ActivityThreadCallback.handleMessage(ActivityThreadCallback.java:74)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7586)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{f029dc8 ActivityRecord{4de7e6b u0 com.hellogeek.fycleanking/cn.jpush.android.service.DActivity t-1 f}}
    at android.os.Parcel.createException(Parcel.java:1957)
    at android.os.Parcel.readException(Parcel.java:1921)
    at android.os.Parcel.readException(Parcel.java:1871)
    at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:8738)
    ... 17 more
Caused by: android.os.RemoteException: Remote stack trace:
    at com.android.server.am.ActivityManagerService.reportSizeConfigurations(Landroid/os/IBinder;[I[I[I)V(libmapleservices.so:5928305)
    at android.app.IActivityManager$Stub.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleframework.so:4772417)
    at com.android.server.am.ActivityManagerService.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleservices.so:5940665)
    at com.android.server.am.HwActivityManagerService.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmaplehwServices.so:3389409)
    at android.os.Binder.execTransact(IJJI)Z(libmapleframework.so:6099637)
java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{f029dc8 ActivityRecord{4de7e6b u0 com.hellogeek.fycleanking/cn.jpush.android.service.DActivity t-1 f}}
    at android.os.Parcel.createException(Parcel.java:1957)
    at android.os.Parcel.readException(Parcel.java:1921)
    at android.os.Parcel.readException(Parcel.java:1871)
    at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:8738)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.xiaoniu.cleanking.room.LoadedApkHuaWei$V28VerifierImpl$AmsInvocationHandler.invoke(LoadedApkHuaWei.java:138)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy5.reportSizeConfigurations(Unknown Source)
    at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:3692)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3652)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:117)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:74)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2209)
    at com.didiglobal.booster.instrument.ActivityThreadCallback.handleMessage(ActivityThreadCallback.java:74)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7586)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: android.os.RemoteException: Remote stack trace:
    at com.android.server.am.ActivityManagerService.reportSizeConfigurations(Landroid/os/IBinder;[I[I[I)V(libmapleservices.so:5928305)
    at android.app.IActivityManager$Stub.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleframework.so:4772417)
    at com.android.server.am.ActivityManagerService.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleservices.so:5940665)
    at com.android.server.am.HwActivityManagerService.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmaplehwServices.so:3389409)
    at android.os.Binder.execTransact(IJJI)Z(libmapleframework.so:6099637)
android.os.RemoteException: Remote stack trace:
    at com.android.server.am.ActivityManagerService.reportSizeConfigurations(Landroid/os/IBinder;[I[I[I)V(libmapleservices.so:5928305)
    at android.app.IActivityManager$Stub.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleframework.so:4772417)
    at com.android.server.am.ActivityManagerService.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleservices.so:5940665)
    at com.android.server.am.HwActivityManagerService.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmaplehwServices.so:3389409)
    at android.os.Binder.execTransact(IJJI)Z(libmapleframework.so:6099637)

**Comment by chenyuEthan111** [comment]
![8b9973bc69fa87bf90a246a454232e4](https://user-images.githubusercontent.com/71430726/97825861-d4a64400-1cfa-11eb-9f8c-f6651c45eded.png)

**Comment by llew2011** [comment]
Caused by: java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{f029dc8 ActivityRecord{4de7e6b u0 com.hellogeek.fycleanking/cn.jpush.android.service.DActivity t-1 f}}
at android.os.Parcel.createException(Parcel.java:1957)
at android.os.Parcel.readException(Parcel.java:1921)
at android.os.Parcel.readException(Parcel.java:1871)
at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:8738)
... 17 more

根据报错看，ActivityRecord找不到，怀疑是Activity被回收了，应该不是当前库的问题
