### ISSUE TITLE
lead to app crash,error log : ACCESS_SERVICE_ERROR', message='060011 : INTERNAL_ERROR

### ISSUE THREAD

**Issue by ShigerD** [llew2011/HuaWeiVerifier#11]
03-09 19:17:33.963 19469 20436 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: opening provider com.huawei.hms.fwkit.provider.HMSFrameworkProvider from ProcessRecord{3abbc50 19469:com.p1.mobile.putong/u0a223} (pid=19469, uid=10223) that is not exported from UID 10075
03-09 19:17:33.963 19469 20436 E AndroidRuntime: at android.os.Parcel.createException(Parcel.java:2071)
03-09 19:17:33.963 19469 20436 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:2039)
03-09 19:17:33.963 19469 20436 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:1987)
03-09 19:17:33.963 19469 20436 E AndroidRuntime: at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5092)
03-09 19:17:33.963 19469 20436 E AndroidRuntime: ... 16 more
03-09 19:17:33.963 19469 20436 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
03-09 19:17:33.963 19469 20436 E AndroidRuntime: at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7366)
03-09 19:17:33.963 19469 20436 E AndroidRuntime: at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7829)
03-09 19:17:33.963 19469 20436 E AndroidRuntime: at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2097)

**Comment by ShigerD** [comment]
part phones in the market will crash when use this lib and map kit version: 5.2.0.301（2021-03-09） 
Crash happen when load the map a few seconds.
