### ISSUE TITLE
仍然有注册上限， 1000 （from Android 9.0）

### ISSUE THREAD

**Issue by Crazy-MT** [llew2011/HuaWeiVerifier#4]
没导入这个库的时候是 250 个注册上限，导入之后是 1000 个上限

**Comment by llew2011** [comment]
机型告诉我一下

**Comment by MTAndroidDev** [comment]
华为荣耀 10

**Comment by llew2011** [comment]
> > 机型告诉我一下
> 
> 我们测试的华为mate20 pro也有这个问题，上限就是1000。
> 而且使用这个库以后多出来很多下面这个异常，目前还没确定是怎么导致的
> android.app.RemoteServiceException: can't deliver broadcast
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2105)
> at android.os.Handler.dispatchMessage(Handler.java:109)
> at android.os.Looper.loop(Looper.java:166)
> at android.app.ActivityThread.main(ActivityThread.java:7383)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

@yan269954107 这个问题应该不是当前库导致的，当前库的作用相当于屏蔽了华为白名单机制...另外看一下这里：[https://stackoverflow.com/questions/40175713/android-getting-cant-deliver-broadcast-error-on-dynamically-registered-broa](https://stackoverflow.com/questions/40175713/android-getting-cant-deliver-broadcast-error-on-dynamically-registered-broa)

**Comment by llew2011** [comment]
> 华为荣耀 10

@MTAndroidDev 麻烦再测试一下，我这边用的荣耀10（Android 8.1.0，API 27）测试注册2000个Broadcast也是OK的

**Comment by MTAndroidDev** [comment]
> > 华为荣耀 10
> 
> @MTAndroidDev 麻烦再测试一下，我这边用的荣耀 10（Android 8.1.0，API 27）测试注册 2000 个 Broadcast 也是 OK 的

我这边是荣耀 10 ， Android 9.0 系统的，多次测试仍然有这个问题。

**Comment by csbz17027** [comment]
大佬，用的1.1.1版本，还是超过1000就崩
java.lang.IllegalStateException

Too many receivers, total of 1000, registered for pid: 10197, callerPackage:

**Comment by llew2011** [comment]
> 大佬，用的1.1.1版本，还是超过1000就崩
> java.lang.IllegalStateException
> 
> Too many receivers, total of 1000, registered for pid: 10197, callerPackage:

@csbz17027  机型告诉我一下

**Comment by csbz17027** [comment]
> > 大佬，用的1.1.1版本，还是超过1000就崩
> > java.lang.IllegalStateException
> > Too many receivers, total of 1000, registered for pid: 10197, callerPackage:
> 
> @csbz17027 机型告诉我一下

都是Android 9,level 28的，荣耀 JSN AL00 ,华为 CLT AL00,华为 HWI AL00
众多华为的机型应该都可以重现。在https://deveco.huawei.com上可以找到相关远程测试机。

**Comment by llew2011** [comment]
> > > 大佬，用的1.1.1版本，还是超过1000就崩
> > > java.lang.IllegalStateException
> > > Too many receivers, total of 1000, registered for pid: 10197, callerPackage:
> > 
> > 
> > @csbz17027 机型告诉我一下
> 
> 都是Android 9,level 28的，荣耀 JSN AL00 ,华为 CLT AL00,华为 HWI AL00
> 众多华为的机型应该都可以重现。在[https://deveco.huawei.com上可以找到相关远程测试机。](https://deveco.huawei.com%E4%B8%8A%E5%8F%AF%E4%BB%A5%E6%89%BE%E5%88%B0%E7%9B%B8%E5%85%B3%E8%BF%9C%E7%A8%8B%E6%B5%8B%E8%AF%95%E6%9C%BA%E3%80%82)

使用1.1.2版本

**Comment by csbz17027** [comment]
> > > > 大佬，用的1.1.1版本，还是超过1000就崩
> > > > java.lang.IllegalStateException
> > > > Too many receivers, total of 1000, registered for pid: 10197, callerPackage:
> > > 
> > > 
> > > @csbz17027 机型告诉我一下
> > 
> > 
> > 都是Android 9,level 28的，荣耀 JSN AL00 ,华为 CLT AL00,华为 HWI AL00
> > 众多华为的机型应该都可以重现。在[https://deveco.huawei.com上可以找到相关远程测试机。](https://deveco.huawei.com%E4%B8%8A%E5%8F%AF%E4%BB%A5%E6%89%BE%E5%88%B0%E7%9B%B8%E5%85%B3%E8%BF%9C%E7%A8%8B%E6%B5%8B%E8%AF%95%E6%9C%BA%E3%80%82)
> 
> 使用1.1.2版本

使用1.1.2版本在注册超过1000时还是依然会crash，在android 9 的荣耀20和P30上都可以重现。
TooManyBroadcastCallback的监听回调是进了的。我现在在考虑当这个触发后不再让注册广播接收器，但问题是大多数广播接收器都是第三方lib中注册的，我又没办法控制，很是蛋疼= =

**Comment by llew2011** [comment]
> > > > > 大佬，用的1.1.1版本，还是超过1000就崩
> > > > > java.lang.IllegalStateException
> > > > > Too many receivers, total of 1000, registered for pid: 10197, callerPackage:
> > > > 
> > > > 
> > > > @csbz17027 机型告诉我一下
> > > 
> > > 
> > > 都是Android 9,level 28的，荣耀 JSN AL00 ,华为 CLT AL00,华为 HWI AL00
> > > 众多华为的机型应该都可以重现。在[https://deveco.huawei.com上可以找到相关远程测试机。](https://deveco.huawei.com%E4%B8%8A%E5%8F%AF%E4%BB%A5%E6%89%BE%E5%88%B0%E7%9B%B8%E5%85%B3%E8%BF%9C%E7%A8%8B%E6%B5%8B%E8%AF%95%E6%9C%BA%E3%80%82)
> > 
> > 
> > 使用1.1.2版本
> 
> 使用1.1.2版本在注册超过1000时还是依然会crash，在android 9 的荣耀20和P30上都可以重现。
> TooManyBroadcastCallback的监听回调是进了的。我现在在考虑当这个触发后不再让注册广播接收器，但问题是大多数广播接收器都是第三方lib中注册的，我又没办法控制，很是蛋疼= =

我用P30测试了下，没有问题，在https://deveco.huawei.com上远程测试，在android 9 的荣耀20和P30上没有重现，确认一下你是否用的是1.1.2版本？
另外可以控制第三方的lib库，可以看下我写的另一个插件：https://github.com/llew2011/BytecodeFixer

**Comment by csbz17027** [comment]
> > > > > > 大佬，用的1.1.1版本，还是超过1000就崩
> > > > > > java.lang.IllegalStateException
> > > > > > Too many receivers, total of 1000, registered for pid: 10197, callerPackage:
> > > > > 
> > > > > 
> > > > > @csbz17027 机型告诉我一下
> > > > 
> > > > 
> > > > 都是Android 9,level 28的，荣耀 JSN AL00 ,华为 CLT AL00,华为 HWI AL00
> > > > 众多华为的机型应该都可以重现。在[https://deveco.huawei.com上可以找到相关远程测试机。](https://deveco.huawei.com%E4%B8%8A%E5%8F%AF%E4%BB%A5%E6%89%BE%E5%88%B0%E7%9B%B8%E5%85%B3%E8%BF%9C%E7%A8%8B%E6%B5%8B%E8%AF%95%E6%9C%BA%E3%80%82)
> > > 
> > > 
> > > 使用1.1.2版本
> > 
> > 
> > 使用1.1.2版本在注册超过1000时还是依然会crash，在android 9 的荣耀20和P30上都可以重现。
> > TooManyBroadcastCallback的监听回调是进了的。我现在在考虑当这个触发后不再让注册广播接收器，但问题是大多数广播接收器都是第三方lib中注册的，我又没办法控制，很是蛋疼= =
> 
> 我用P30测试了下，没有问题，在[https://deveco.huawei.com上远程测试，在android](https://deveco.huawei.com%E4%B8%8A%E8%BF%9C%E7%A8%8B%E6%B5%8B%E8%AF%95%EF%BC%8C%E5%9C%A8android) 9 的荣耀20和P30上没有重现，确认一下你是否用的是1.1.2版本？
> 另外可以控制第三方的lib库，可以看下我写的另一个插件：https://github.com/llew2011/BytecodeFixer

我 External Libraries 下确实显示的是1.1.2版本。
在application的onCreate方法中添加`LoadedApkHuaWei.hookHuaWeiVerifier(this);`
测试的方式是在启动页
` IntentFilter filter = new IntentFilter();
        for (int i = 0; i < 1000; i++) {
            registerReceiver(new BroadcastReceiver() {
                @Override
                public void onReceive(Context context, Intent intent) {

                }
            }, filter);
            System.out.println("register:" + i);
        }`

**Comment by wuxianghua** [comment]
> > > > > > > 大佬，用的1.1.1版本，还是超过1000就崩
> > > > > > > java.lang.IllegalStateException
> > > > > > > Too many receivers, total of 1000, registered for pid: 10197, callerPackage:
> > > > > > 
> > > > > > 
> > > > > > @csbz17027 机型告诉我一下
> > > > > 
> > > > > 
> > > > > 都是Android 9,level 28的，荣耀 JSN AL00 ,华为 CLT AL00,华为 HWI AL00
> > > > > 众多华为的机型应该都可以重现。在[https://deveco.huawei.com上可以找到相关远程测试机。](https://deveco.huawei.com%E4%B8%8A%E5%8F%AF%E4%BB%A5%E6%89%BE%E5%88%B0%E7%9B%B8%E5%85%B3%E8%BF%9C%E7%A8%8B%E6%B5%8B%E8%AF%95%E6%9C%BA%E3%80%82)
> > > > 
> > > > 
> > > > 使用1.1.2版本
> > > 
> > > 
> > > 使用1.1.2版本在注册超过1000时还是依然会crash，在android 9 的荣耀20和P30上都可以重现。
> > > TooManyBroadcastCallback的监听回调是进了的。我现在在考虑当这个触发后不再让注册广播接收器，但问题是大多数广播接收器都是第三方lib中注册的，我又没办法控制，很是蛋疼= =
> > 
> > 
> > 我用P30测试了下，没有问题，在[https://deveco.huawei.com上远程测试，在android](https://deveco.huawei.com%E4%B8%8A%E8%BF%9C%E7%A8%8B%E6%B5%8B%E8%AF%95%EF%BC%8C%E5%9C%A8android) 9 的荣耀20和P30上没有重现，确认一下你是否用的是1.1.2版本？
> > 另外可以控制第三方的lib库，可以看下我写的另一个插件：https://github.com/llew2011/BytecodeFixer
> 
> 我 External Libraries 下确实显示的是1.1.2版本。
> 在application的onCreate方法中添加`LoadedApkHuaWei.hookHuaWeiVerifier(this);`
> 测试的方式是在启动页
> ` IntentFilter filter = new IntentFilter();
> for (int i = 0; i < 1000; i++) {
> registerReceiver(new BroadcastReceiver() {
> @override
> public void onReceive(Context context, Intent intent) {
> 
> ```
>             }
>         }, filter);
>         System.out.println("register:" + i);
>     }`
> ```

我这边也发现了这个崩溃了 
java.lang.IllegalStateException:Too many receivers, total of 1000, registered for pid: 5868, callerPackage: com.appbox.livemall
android.os.Parcel.createException(Parcel.java:1961)
Caused by:
android.os.RemoteException:Remote stack trace:
at com.android.server.am.ActivityManagerService.registerReceiver(ActivityManagerService.java:22830)
at android.app.IActivityManager$Stub.onTransact$registerReceiver$(IActivityManager.java:10158)
at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:154)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3654)
at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:609)

是在Android9.0,Level 28 的版本上发现的
机型有：荣耀HLK AL00
              华为GLK AL00
              华为INE AL00

这个问题已经解决了吗

**Comment by llew2011** [comment]
找了荣耀AGS2-W09HN(Android 9 API 28)的设备做了下调试，没有crash，我再找下上述设备试试
